/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package poo.cap1.ej2;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class GUIConejos extends javax.swing.JFrame {

    Conejo misConejos[]; //declarando un arreglo
    DefaultTableModel dtmModelo; //logico
    final int TAMANIO_ARREGLO = 4;
    int contador;

    /**
     * Creates new form NewJFrame
     */
    public GUIConejos() {
        initComponents();
        dtmModelo = new DefaultTableModel();
        dtmModelo.addColumn("Nombre");
        dtmModelo.addColumn("Edad");
        dtmModelo.addColumn("Peso");
        dtmModelo.addColumn("Sexo");
        dtmModelo.addColumn("Tasa Crecimiento");
        dtmModelo.addColumn("Raza");
        dtmModelo.addColumn("Dieta");
        tblDatos.setModel(dtmModelo);//colocando el modelo para que se presente visualmente en la tabla
        misConejos = new Conejo[TAMANIO_ARREGLO];//reservando espacio para un arreglo de 4 elementos de la clase Conejo
        contador = 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgSexo = new javax.swing.ButtonGroup();
        pnlDatosGenerales = new javax.swing.JPanel();
        txtEdad = new javax.swing.JTextField();
        txtTasaCrecimiento = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        lblPeso = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtPeso = new javax.swing.JTextField();
        lbltasadecrecimiento = new javax.swing.JLabel();
        lblEdad = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cmbRaza = new javax.swing.JComboBox<>();
        btnGuardar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        rbtMacho = new javax.swing.JRadioButton();
        rbtHembra = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        chkAlfalfa = new javax.swing.JCheckBox();
        chkHeno = new javax.swing.JCheckBox();
        chkZanahoria = new javax.swing.JCheckBox();
        chkFrutas = new javax.swing.JCheckBox();
        btnVerRegistros = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDatos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlDatosGenerales.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Generales"));

        lblNombre.setText("Nombre");

        lblPeso.setText("Peso");

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        txtPeso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesoActionPerformed(evt);
            }
        });

        lbltasadecrecimiento.setText("Tasa Crecimiento");

        lblEdad.setText("Edad");

        jLabel3.setText("Raza");

        cmbRaza.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Angora", "Cabeza de Leon", "Californiano", "Papillon", "Renard" }));
        cmbRaza.setSelectedIndex(-1);
        cmbRaza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbRazaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlDatosGeneralesLayout = new javax.swing.GroupLayout(pnlDatosGenerales);
        pnlDatosGenerales.setLayout(pnlDatosGeneralesLayout);
        pnlDatosGeneralesLayout.setHorizontalGroup(
            pnlDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosGeneralesLayout.createSequentialGroup()
                .addGroup(pnlDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDatosGeneralesLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lbltasadecrecimiento))
                    .addGroup(pnlDatosGeneralesLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(lblEdad))
                    .addGroup(pnlDatosGeneralesLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel3)))
                .addGap(18, 18, 18)
                .addGroup(pnlDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cmbRaza, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtTasaCrecimiento)
                    .addComponent(txtEdad))
                .addGap(65, 65, 65)
                .addGroup(pnlDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPeso)
                    .addComponent(lblNombre))
                .addGap(51, 51, 51)
                .addGroup(pnlDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                    .addComponent(txtPeso))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        pnlDatosGeneralesLayout.setVerticalGroup(
            pnlDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosGeneralesLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(pnlDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblEdad)
                        .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblNombre)))
                .addGap(18, 18, 18)
                .addGroup(pnlDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbltasadecrecimiento)
                    .addComponent(txtTasaCrecimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPeso)
                    .addComponent(txtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbRaza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
        );

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Sexo"));

        btgSexo.add(rbtMacho);
        rbtMacho.setText("Macho");

        btgSexo.add(rbtHembra);
        rbtHembra.setText("Hembra");
        rbtHembra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtHembraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbtHembra)
                    .addComponent(rbtMacho))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(rbtMacho)
                .addGap(18, 18, 18)
                .addComponent(rbtHembra)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Dieta"));

        chkAlfalfa.setText("Alfalfa");

        chkHeno.setText("Heno");

        chkZanahoria.setText("Zanahoria");

        chkFrutas.setText("Frutas");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkFrutas, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(chkZanahoria)
                        .addComponent(chkHeno, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(chkAlfalfa, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(chkAlfalfa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chkHeno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chkZanahoria)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chkFrutas)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnVerRegistros.setText("Ver registros");
        btnVerRegistros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerRegistrosActionPerformed(evt);
            }
        });

        tblDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblDatos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(308, 308, 308)
                        .addComponent(btnGuardar)
                        .addGap(69, 69, 69)
                        .addComponent(btnVerRegistros))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 864, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(pnlDatosGenerales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlDatosGenerales, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnVerRegistros))
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:

        try {
            int edad = Integer.parseInt(txtEdad.getText());;
            double tasaCrecimiento = Double.parseDouble(txtTasaCrecimiento.getText());
            String nombre = txtNombre.getText();
            double peso = Double.parseDouble(txtPeso.getText());

            String raza = (String) cmbRaza.getSelectedItem();
            String sexo = "";
            if (rbtHembra.isSelected()) {
                sexo = "Hembra";
            }
            if (rbtMacho.isSelected()) {
                sexo = "Macho";
            }

            String dieta = "";
            String[] alimentosSeleccionados = new String[4];
            int indice = 0;
            if (chkAlfalfa.isSelected()) {
                dieta += chkAlfalfa.getText();
                alimentosSeleccionados[indice] = chkAlfalfa.getText();
                indice++;
            }

            if (chkFrutas.isSelected()) {
                dieta += chkFrutas.getText();
                alimentosSeleccionados[indice] = chkFrutas.getText();
                indice++;
            }
            if (chkHeno.isSelected()) {
                dieta += chkHeno.getText();
                alimentosSeleccionados[indice] = chkHeno.getText();
                indice++;
            }

            if (chkZanahoria.isSelected()) {
                dieta += chkZanahoria.getText();
                alimentosSeleccionados[indice] = chkZanahoria.getText();
            }
            if (contador < misConejos.length) {
                misConejos[contador] = new Conejo(edad, peso, tasaCrecimiento, nombre,001);
                misConejos[contador].setSexo(sexo);
                misConejos[contador].setRaza(raza);
                misConejos[contador].setAlimentosFavoritos(alimentosSeleccionados);
                contador++;
            }
        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(rootPane, "Debe ingresar un numero"
                    + "para la edad, el peso y la tasa de crecimiento", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtPesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesoActionPerformed

    private void rbtHembraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtHembraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtHembraActionPerformed

    private void btnVerRegistrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerRegistrosActionPerformed
        // TODO add your handling code here:
      /*  for (int i = 0; i < misConejos.length; i++)
          //  System.out.println(misConejos[i].getNombre()+misConejos[i].getEdad());
        dtmModelo.addRow(new Object[]{misConejos[i].getNombre(), misConejos[i].getEdad(),
                misConejos[i].getPeso(), misConejos[i].getSexo(), misConejos[i].getTasaCrecimientoPorcentual(),
        misConejos[i].getRaza(),misConejos[i].mostrarAlimentosFavoritos()}); */
      
      for (Conejo c: misConejos ){
          dtmModelo.addRow(new Object[]{c.getNombre(),c.getEdad(), c.getPeso(),
          c.getSexo(), c.getTasaCrecimientoPorcentual(), c.getRaza(), c.mostrarAlimentosFavoritos()});
      }
         
    }//GEN-LAST:event_btnVerRegistrosActionPerformed

    private void cmbRazaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbRazaActionPerformed
        // TODO add your handling code here:
        String raza = (String) cmbRaza.getSelectedItem();
        JOptionPane.showMessageDialog(rootPane, "La raza seleccionada es "+ cmbRaza.getSelectedItem());
    }//GEN-LAST:event_cmbRazaActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(rootPane, "El nombre ingresado es "+ txtNombre.getText());
    }//GEN-LAST:event_txtNombreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIConejos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIConejos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIConejos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIConejos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIConejos().setVisible(true);
            }
        });
    }

    private void limpiarGUI() {
        //la GUI debe aparecer lista para que el usr ingrese datos nuevamente
        txtEdad.setText("");
        txtNombre.setText("");
        txtPeso.setText("");
        txtTasaCrecimiento.setText(null);
        chkAlfalfa.setSelected(false); //para deseleccionar un componente individual
        chkHeno.setSelected(false);
        chkZanahoria.setSelected(false);
        btgSexo.clearSelection(); //para deseleccionar el radio button de UN GRUPO
        cmbRaza.setSelectedIndex(-1);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btgSexo;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnVerRegistros;
    private javax.swing.JCheckBox chkAlfalfa;
    private javax.swing.JCheckBox chkFrutas;
    private javax.swing.JCheckBox chkHeno;
    private javax.swing.JCheckBox chkZanahoria;
    private javax.swing.JComboBox<String> cmbRaza;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEdad;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPeso;
    private javax.swing.JLabel lbltasadecrecimiento;
    private javax.swing.JPanel pnlDatosGenerales;
    private javax.swing.JRadioButton rbtHembra;
    private javax.swing.JRadioButton rbtMacho;
    private javax.swing.JTable tblDatos;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPeso;
    private javax.swing.JTextField txtTasaCrecimiento;
    // End of variables declaration//GEN-END:variables
}
