/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package poo.cap1.ej2;

import java.util.ArrayList;
import java.util.Collections;
import java.util.StringTokenizer;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class GUIConejo extends javax.swing.JFrame {
    
    Conejo miConejo;
    int idInicial = 1001;
    static ArrayList <Conejo> conejos;
    ArrayList<Conejo> conejos2;

    /**
     * Creates new form NewJFrame
     */
    public GUIConejo() {
        initComponents();
        lblMensajeErrorNombre.setVisible(false);
        conejos = new ArrayList<Conejo>();
        conejos2 = new ArrayList<>();
        Collections.sort(conejos2);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgSexo = new javax.swing.ButtonGroup();
        jComboBox1 = new javax.swing.JComboBox<>();
        pnlDatosGenerales = new javax.swing.JPanel();
        txtEdad = new javax.swing.JTextField();
        txtTasaCrecimiento = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        lblPeso = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtPeso = new javax.swing.JTextField();
        lbltasadecrecimiento = new javax.swing.JLabel();
        lblEdad = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cmbRaza = new javax.swing.JComboBox<>();
        lblMensajeErrorNombre = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaInformacion = new javax.swing.JTextArea();
        btnGuardar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        rbtMacho = new javax.swing.JRadioButton();
        rbtHembra = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        chkAlfalfa = new javax.swing.JCheckBox();
        chkHeno = new javax.swing.JCheckBox();
        chkZanahoria = new javax.swing.JCheckBox();
        chkFrutas = new javax.swing.JCheckBox();
        btnDiagnosticar = new javax.swing.JButton();
        txtDiagnostico = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txaDieta = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txaDescripcion = new javax.swing.JTextArea();
        btnContarOraciones = new javax.swing.JButton();
        btnContarPalabras = new javax.swing.JButton();
        btnGuardarDescripcion = new javax.swing.JButton();
        btnContar = new javax.swing.JButton();
        btnVerEdad = new javax.swing.JButton();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        pnlDatosGenerales.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Generales"));

        txtEdad.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEdadFocusLost(evt);
            }
        });

        txtTasaCrecimiento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTasaCrecimientoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTasaCrecimientoFocusLost(evt);
            }
        });

        lblNombre.setText("Nombre");

        lblPeso.setText("Peso");

        txtNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNombreFocusLost(evt);
            }
        });
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNombreKeyReleased(evt);
            }
        });

        txtPeso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesoActionPerformed(evt);
            }
        });

        lbltasadecrecimiento.setText("Tasa Crecimiento");

        lblEdad.setText("Edad");

        jLabel3.setText("Raza");

        cmbRaza.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Angora", "Cabeza de Leon", "Californiano", "Papillon", "Renard" }));
        cmbRaza.setSelectedIndex(-1);

        lblMensajeErrorNombre.setForeground(new java.awt.Color(255, 0, 51));
        lblMensajeErrorNombre.setText("Debe ingresar letras");

        javax.swing.GroupLayout pnlDatosGeneralesLayout = new javax.swing.GroupLayout(pnlDatosGenerales);
        pnlDatosGenerales.setLayout(pnlDatosGeneralesLayout);
        pnlDatosGeneralesLayout.setHorizontalGroup(
            pnlDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosGeneralesLayout.createSequentialGroup()
                .addGroup(pnlDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDatosGeneralesLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lbltasadecrecimiento))
                    .addGroup(pnlDatosGeneralesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblEdad))
                    .addGroup(pnlDatosGeneralesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)))
                .addGap(18, 18, 18)
                .addGroup(pnlDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbRaza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtTasaCrecimiento, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                        .addComponent(txtEdad, javax.swing.GroupLayout.Alignment.LEADING)))
                .addGap(49, 49, 49)
                .addGroup(pnlDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombre)
                    .addComponent(lblPeso))
                .addGap(26, 26, 26)
                .addGroup(pnlDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblMensajeErrorNombre)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        pnlDatosGeneralesLayout.setVerticalGroup(
            pnlDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosGeneralesLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(pnlDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEdad)
                    .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMensajeErrorNombre))
                .addGap(18, 18, 18)
                .addGroup(pnlDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbltasadecrecimiento)
                    .addComponent(txtTasaCrecimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPeso)
                    .addComponent(txtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(pnlDatosGeneralesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbRaza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
        );

        txaInformacion.setColumns(20);
        txaInformacion.setRows(5);
        jScrollPane1.setViewportView(txaInformacion);

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Sexo"));

        btgSexo.add(rbtMacho);
        rbtMacho.setText("Macho");

        btgSexo.add(rbtHembra);
        rbtHembra.setText("Hembra");
        rbtHembra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtHembraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbtHembra)
                    .addComponent(rbtMacho))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(rbtMacho)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(rbtHembra)
                .addGap(37, 37, 37))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Dieta"));

        chkAlfalfa.setText("Alfalfa");

        chkHeno.setText("Heno");

        chkZanahoria.setText("Zanahoria");

        chkFrutas.setText("Frutas");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkFrutas, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(chkZanahoria)
                        .addComponent(chkHeno, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(chkAlfalfa, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(152, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(chkAlfalfa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chkHeno)
                .addGap(6, 6, 6)
                .addComponent(chkZanahoria)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkFrutas, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnDiagnosticar.setText("Diagnosticar");
        btnDiagnosticar.setEnabled(false);
        btnDiagnosticar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDiagnosticarActionPerformed(evt);
            }
        });

        txaDieta.setColumns(20);
        txaDieta.setRows(5);
        jScrollPane2.setViewportView(txaDieta);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Descripción"));

        txaDescripcion.setColumns(20);
        txaDescripcion.setRows(5);
        jScrollPane3.setViewportView(txaDescripcion);

        btnContarOraciones.setText("Contar Oraciones");
        btnContarOraciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContarOracionesActionPerformed(evt);
            }
        });

        btnContarPalabras.setText("Contar palabras");
        btnContarPalabras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContarPalabrasActionPerformed(evt);
            }
        });

        btnGuardarDescripcion.setText("Guardar Descripción");
        btnGuardarDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarDescripcionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnContarOraciones, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardarDescripcion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(btnContarPalabras, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnContarOraciones)
                            .addComponent(btnContarPalabras))
                        .addGap(29, 29, 29)
                        .addComponent(btnGuardarDescripcion))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        btnContar.setText("Contar Conejos Creados");
        btnContar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContarActionPerformed(evt);
            }
        });

        btnVerEdad.setText("Ver edad conejo adulto");
        btnVerEdad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerEdadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(pnlDatosGenerales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtDiagnostico, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1020, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(299, 299, 299)
                                .addComponent(btnGuardar)
                                .addGap(26, 26, 26)
                                .addComponent(btnDiagnosticar)
                                .addGap(82, 82, 82)
                                .addComponent(btnContar, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)
                                .addComponent(btnVerEdad)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnlDatosGenerales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnDiagnosticar)
                    .addComponent(btnContar)
                    .addComponent(btnVerEdad))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDiagnostico, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        //     JOptionPane.showMessageDialog(null, "Fin de la clase", "Despedida", JOptionPane.PLAIN_MESSAGE);
        //colocar 2 variables de tipo string para edad y tasa crecimiento
        //colocar en esas variables el contenido de las cajas de texto
        String edad = txtEdad.getText();
        String tasaCrecimiento = txtTasaCrecimiento.getText();
        String nombre = txtNombre.getText();
        String peso = txtPeso.getText();
        
        try {
            int edadConejo = Integer.parseInt(txtEdad.getText());
            miConejo = new Conejo(Integer.parseInt(edad), Double.parseDouble(peso),
                    Double.parseDouble(tasaCrecimiento), nombre, idInicial);
            idInicial++;
            String raza = (String) cmbRaza.getSelectedItem();
            miConejo.setRaza(raza); //NullPointerException
            if (rbtHembra.isSelected()) {
                miConejo.setSexo("Hembra");
            }
            if (rbtMacho.isSelected()) {
                miConejo.setSexo("Macho");
            }
            
            String dieta = "";
            //crear un arreglo para guardar todas las opciones de dieta
            //que selecciono el USR para ese conejo
            String[] alimentosSeleccionados = new String[4];
            int indice = 0;
            if (chkAlfalfa.isSelected()) {
                dieta += chkAlfalfa.getText();
                alimentosSeleccionados[indice] = chkAlfalfa.getText();
                indice++;
            }
            
            if (chkHeno.isSelected()) {
                dieta += chkHeno.getText();
                alimentosSeleccionados[indice] = chkHeno.getText();
                indice++;
            }
            
            if (chkZanahoria.isSelected()) {
                dieta += chkZanahoria.getText();
                alimentosSeleccionados[indice] = chkZanahoria.getText();
                indice++;
            }
            
            miConejo.setDieta(dieta); //excepcion
            miConejo.setAlimentosFavoritos(alimentosSeleccionados);
            txaDieta.setText(miConejo.mostrarAlimentosFavoritos());
            for (int i = 0; i < alimentosSeleccionados.length; i++) {
                // JOptionPane.showMessageDialog(rootPane, "En el indice "+i+" se guarda el texto "+alimentosSeleccionados[i]);
            }

            //  for(String a: alimentosSeleccionados)// for each ---no usa el indice, se usa un identificador para el elemento del arreglo
            //  JOptionPane.showMessageDialog(rootPane, "El texto es "+a);
            //el area de texto debe presentar la info de todos los conejos creados
            txaInformacion.setText(txaInformacion.getText() + miConejo.toString() + "\n");
            btnDiagnosticar.setEnabled(true); //habilitar el btn diagnosticar

            /*  StringTokenizer tokens = new StringTokenizer(txaCaracteristicas.getText());
            JOptionPane.showMessageDialog(rootPane, "Se obtuvieron " + tokens.countTokens() + " caracteristicas");

            while (tokens.hasMoreTokens()) {
                JOptionPane.showMessageDialog(rootPane, tokens.nextToken());
            }*/
            
            conejos.add(miConejo);
            
        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(rootPane, "Debe ingresar un numero"
                    + "para la edad, el peso y la tasa de crecimiento", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (NullPointerException npe) {
            JOptionPane.showMessageDialog(rootPane, "El conejo no se guardo ", "ERROR", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Otro error" + e.toString());
        }
        
        limpiarGUI();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtPesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesoActionPerformed

    private void rbtHembraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtHembraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtHembraActionPerformed

    private void btnDiagnosticarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDiagnosticarActionPerformed
        // TODO add your handling code here:
        Veterinario vet = new Veterinario();
        String diagnostico = vet.diagnosticarConejo(miConejo);
        txtDiagnostico.setText(diagnostico);
    }//GEN-LAST:event_btnDiagnosticarActionPerformed

    private void txtEdadFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEdadFocusLost
        // TODO add your handling code here:

    }//GEN-LAST:event_txtEdadFocusLost

    private void txtNombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombreFocusLost
        // TODO add your handling code here:
        //JOptionPane.showMessageDialog(rootPane, "***");
        // if (!Validador.validarNombre(txtNombre.getText()))
        //   lblMensaje.setVisible(true);
    }//GEN-LAST:event_txtNombreFocusLost

    private void txtNombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyReleased
        // TODO add your handling code here:
        //1. invocar un metodo para validar el nombre del conejo
        //LOLA, lolA, LoLa, ana, PP, Jaq
        
        if (Validador.validarNombre(txtNombre.getText()))
            lblMensajeErrorNombre.setVisible(false);
        else{
            lblMensajeErrorNombre.setVisible(true);
           // JOptionPane.showMessageDialog(rootPane, "Debe ingresar letras", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
       
    }//GEN-LAST:event_txtNombreKeyReleased

    private void txtTasaCrecimientoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTasaCrecimientoFocusGained
        // TODO add your handling code here:
        //  JOptionPane.showMessageDialog(rootPane, "Puede ingresar la tasa de crecimiento");
    }//GEN-LAST:event_txtTasaCrecimientoFocusGained

    private void txtTasaCrecimientoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTasaCrecimientoFocusLost
        // TODO add your handling code here:
        // JOptionPane.showMessageDialog(rootPane, "Focus Lost para tasa de crecimiento");
    }//GEN-LAST:event_txtTasaCrecimientoFocusLost

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void btnContarPalabrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContarPalabrasActionPerformed
        // TODO add your handling code here:
        //la cadena delimitadora es un espacio, tab, salto linea
        StringTokenizer tokensDePalabra = new StringTokenizer(txaDescripcion.getText());
        JOptionPane.showMessageDialog(rootPane, "La cantidad de palabras es "+tokensDePalabra.countTokens());
    }//GEN-LAST:event_btnContarPalabrasActionPerformed

    private void btnContarOracionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContarOracionesActionPerformed
        // TODO add your handling code here:
        StringTokenizer tokensDeOraciones = new StringTokenizer(txaDescripcion.getText(),".");
        JOptionPane.showMessageDialog(rootPane, "La cantidad de oraciones es "+tokensDeOraciones.countTokens());
        while (tokensDeOraciones.hasMoreTokens())
            JOptionPane.showMessageDialog(rootPane, tokensDeOraciones.nextToken());
    }//GEN-LAST:event_btnContarOracionesActionPerformed

    private void btnGuardarDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarDescripcionActionPerformed
        // TODO add your handling code here:
        //utilizar el metodo split de String para obtener un arreglo de oraciones
        String oraciones[] = txaDescripcion.getText().split("\\s*\\.\\s*");
        miConejo.setDescripcion(oraciones);
        for(int i=0; i<miConejo.getDescripcion().length; i++){
            txaDescripcion.setText(txaDescripcion.getText()+"\nEn el indice "+i+" se encuentra la descripcion\n"+
                    miConejo.getDescripcion()[i]);
        }
        
    }//GEN-LAST:event_btnGuardarDescripcionActionPerformed

    private void btnContarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContarActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(rootPane, "Los conejos creados son "+Conejo.getContadorConejos());
    }//GEN-LAST:event_btnContarActionPerformed

    private void btnVerEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerEdadActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(rootPane, "Un conejo es adulto a los  "+Conejo.getEdadConejoAdulto()+" dias de nacido");
    }//GEN-LAST:event_btnVerEdadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIConejo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIConejo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIConejo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIConejo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIConejo().setVisible(true);
            }
        });
    }
    
    private void limpiarGUI() {
        //la GUI debe aparecer lista para que el usr ingrese datos nuevamente
        txtEdad.setText("");
        txtNombre.setText("");
        txtPeso.setText("");
        txtTasaCrecimiento.setText(null);
        chkAlfalfa.setSelected(false); //para deseleccionar un componente individual
        chkHeno.setSelected(false);
        chkZanahoria.setSelected(false);
        btgSexo.clearSelection(); //para deseleccionar el radio button de UN GRUPO
        cmbRaza.setSelectedIndex(-1);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btgSexo;
    private javax.swing.JButton btnContar;
    private javax.swing.JButton btnContarOraciones;
    private javax.swing.JButton btnContarPalabras;
    private javax.swing.JButton btnDiagnosticar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnGuardarDescripcion;
    private javax.swing.JButton btnVerEdad;
    private javax.swing.JCheckBox chkAlfalfa;
    private javax.swing.JCheckBox chkFrutas;
    private javax.swing.JCheckBox chkHeno;
    private javax.swing.JCheckBox chkZanahoria;
    private javax.swing.JComboBox<String> cmbRaza;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblEdad;
    private javax.swing.JLabel lblMensajeErrorNombre;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPeso;
    private javax.swing.JLabel lbltasadecrecimiento;
    private javax.swing.JPanel pnlDatosGenerales;
    private javax.swing.JRadioButton rbtHembra;
    private javax.swing.JRadioButton rbtMacho;
    private javax.swing.JTextArea txaDescripcion;
    private javax.swing.JTextArea txaDieta;
    private javax.swing.JTextArea txaInformacion;
    private javax.swing.JTextField txtDiagnostico;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPeso;
    private javax.swing.JTextField txtTasaCrecimiento;
    // End of variables declaration//GEN-END:variables
}
