/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.paa.vista;

import com.paa.modelo.Nivel;
import java.util.ArrayList;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;

/**
 *
 * @author Marcela
 */
public class PnlNivel extends javax.swing.JPanel {

    /**
     * Creates new form PnlNivel
     */
    public PnlNivel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        chkExpresionOral = new javax.swing.JCheckBox();
        chkUsoDeTI = new javax.swing.JCheckBox();
        chkIngles = new javax.swing.JCheckBox();
        chkCapacidadAnalisis = new javax.swing.JCheckBox();
        chkRazonamiento = new javax.swing.JCheckBox();
        chkCompresion = new javax.swing.JCheckBox();
        txtNombre = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(550, 300));

        jLabel1.setText("Nombre");

        jLabel2.setText("Requisitos");

        chkExpresionOral.setText("Expresión Oral");

        chkUsoDeTI.setText("Uso de TI");

        chkIngles.setText("Nivel básico de Inglés");

        chkCapacidadAnalisis.setText("Capacidad Análisis");

        chkRazonamiento.setText("Razonamiento Numérico");

        chkCompresion.setText("Compresión Lectora");

        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(64, 64, 64)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkExpresionOral)
                            .addComponent(chkUsoDeTI))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(chkIngles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(chkCapacidadAnalisis)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkCompresion)
                            .addComponent(chkRazonamiento))))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkExpresionOral)
                    .addComponent(chkIngles)
                    .addComponent(chkRazonamiento))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkUsoDeTI)
                    .addComponent(chkCapacidadAnalisis)
                    .addComponent(chkCompresion))
                .addGap(26, 26, 26)
                .addComponent(jButton1)
                .addContainerGap(42, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ArrayList <String> requisitos = new ArrayList<>();
        if(chkCapacidadAnalisis.isSelected())
            requisitos.add(chkCapacidadAnalisis.getText());
        if(chkCompresion.isSelected())
            requisitos.add(chkCompresion.getText());
        if(chkExpresionOral.isSelected())
            requisitos.add(chkExpresionOral.getText());
        if(chkIngles.isSelected())
            requisitos.add(chkIngles.getText());
        if(chkRazonamiento.isSelected())
            requisitos.add(chkRazonamiento.getText());
        if(chkUsoDeTI.isSelected())
            requisitos.add(chkUsoDeTI.getText());
        FrmMenuPrincipal.niveles.add(new Nivel(txtNombre.getText(), requisitos));
        JOptionPane.showMessageDialog(null, "El nivel se registró con éxito.");
    }//GEN-LAST:event_jButton1ActionPerformed

    public void limpiarPanel(){
        chkCapacidadAnalisis.setSelected(false);
        chkCompresion.setSelected(false);
        chkExpresionOral.setSelected(false);
        chkIngles.setSelected(false);
        chkRazonamiento.setSelected(false);
        chkUsoDeTI.setSelected(false);
        txtNombre.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chkCapacidadAnalisis;
    private javax.swing.JCheckBox chkCompresion;
    private javax.swing.JCheckBox chkExpresionOral;
    private javax.swing.JCheckBox chkIngles;
    private javax.swing.JCheckBox chkRazonamiento;
    private javax.swing.JCheckBox chkUsoDeTI;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
