/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package poo.interfaz;

import java.util.LinkedList;
import javax.swing.JOptionPane;

/**
 *
 * @author FAMILIA Cach
 */
public class AgregarCurso extends javax.swing.JPanel {

    static Registros registro4 = new Registros();
    
    public AgregarCurso() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAgregarCurso = new javax.swing.JLabel();
        lblNombreC = new javax.swing.JLabel();
        lblDescripC = new javax.swing.JLabel();
        lblDuracionC = new javax.swing.JLabel();
        lblReqEspecif = new javax.swing.JLabel();
        cmbCatCurso = new javax.swing.JComboBox();
        txtNombreC = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtaDescripC = new javax.swing.JTextArea();
        txtDuracionC = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtaReqEspesifC = new javax.swing.JTextArea();
        btnRegistrarC = new javax.swing.JButton();
        btnAct = new javax.swing.JButton();

        setBackground(new java.awt.Color(135, 167, 231));

        lblAgregarCurso.setFont(new java.awt.Font("Myanmar Text", 0, 12)); // NOI18N
        lblAgregarCurso.setText("Agregar Curso:");

        lblNombreC.setFont(new java.awt.Font("Myanmar Text", 0, 12)); // NOI18N
        lblNombreC.setText("Nombre del Curso:");

        lblDescripC.setFont(new java.awt.Font("Myanmar Text", 0, 12)); // NOI18N
        lblDescripC.setText("Descripción:");

        lblDuracionC.setFont(new java.awt.Font("Myanmar Text", 0, 12)); // NOI18N
        lblDuracionC.setText("Duración del Curso:");

        lblReqEspecif.setFont(new java.awt.Font("Myanmar Text", 0, 12)); // NOI18N
        lblReqEspecif.setText("Requisitos Específicos");

        cmbCatCurso.setFont(new java.awt.Font("Myanmar Text", 0, 12)); // NOI18N
        cmbCatCurso.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Categorías" }));
        cmbCatCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCatCursoActionPerformed(evt);
            }
        });

        txtaDescripC.setColumns(20);
        txtaDescripC.setRows(5);
        jScrollPane1.setViewportView(txtaDescripC);

        txtaReqEspesifC.setColumns(20);
        txtaReqEspesifC.setRows(5);
        jScrollPane2.setViewportView(txtaReqEspesifC);

        btnRegistrarC.setFont(new java.awt.Font("Myanmar Text", 1, 12)); // NOI18N
        btnRegistrarC.setText("Agregar Curso");
        btnRegistrarC.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRegistrarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarCActionPerformed(evt);
            }
        });

        btnAct.setText("Actualizar");
        btnAct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAgregarCurso)
                            .addComponent(lblNombreC)
                            .addComponent(lblReqEspecif)
                            .addComponent(lblDuracionC)
                            .addComponent(lblDescripC))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtDuracionC, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtNombreC, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                                .addComponent(jScrollPane2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cmbCatCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAct, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(btnRegistrarC, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAgregarCurso)
                    .addComponent(cmbCatCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAct))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(lblDescripC))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombreC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNombreC))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDuracionC)
                    .addComponent(txtDuracionC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblReqEspecif)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRegistrarC)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    public LinkedList<Curso> pasarCurso(){
        return registro4.curso; 
    }
    private void btnRegistrarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarCActionPerformed
        // TODO add your handling code here:
        try{
        Categoria aux;
        Curso auxC;
        String nombreCur=(String)txtNombreC.getText();
        String decripCur=txtaDescripC.getText();
        int duracCur=Integer.parseInt(txtDuracionC.getText());
        String reqEspecifCur=txtaReqEspesifC.getText();
        String opcionCat=(String)cmbCatCurso.getSelectedItem();
        
        if(!"".equals(nombreCur)&& opcionCat!="Categorias"){
            System.out.println("A");
            registro4.curso.add(new Curso(nombreCur,decripCur,duracCur,reqEspecifCur));
            
            //registro4.curDisponible.cmbCursosM.addItem(registro4.curso.get(registro4.curso.size()-1).getNombre());
            //registro4.regDocente.cmbCursoProfe.addItem(registro4.curso.get(registro4.curso.size()-1).getNombre());
            System.out.println("B");
            
            for(int i=0;i<registro4.categorias.size();i++){
                System.out.println("C");
                aux=registro4.categorias.get(i);
                if(opcionCat==registro4.categorias.get(i).getNombre()){
                    System.out.println("D");
                    for(int j=0;j<registro4.curso.size();j++){
                        System.out.println("E");
                        System.out.println(registro4.curso.get(j).getNombre());
                        auxC=registro4.curso.get(j);
                        if(nombreCur==registro4.curso.get(j).getNombre()){
                            System.out.println("F");
                            registro4.curso.get(j).setCategoria(aux);
                        }
                    }
                  
                }
            }
            JOptionPane.showMessageDialog(null, "Curso regitrado exitosamente");
        }else{
            JOptionPane.showMessageDialog(null, "Es nesesario que el curso tenga un nombre y una categoría",
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
        }catch(Exception e){
            //JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_btnRegistrarCActionPerformed

    private void cmbCatCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCatCursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbCatCursoActionPerformed

    private void btnActActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActActionPerformed
        //registro4
        cmbCatCurso.removeAllItems();
        AgregarCategoria obj=new AgregarCategoria();
        LinkedList<Categoria> categorias= new LinkedList<>();
        categorias=obj.pasarCategoria();
        for(Categoria c:obj.pasarCategoria()){
            cmbCatCurso.addItem(c.getNombre());
            //System.out.println(categorias.size());
        }
    }//GEN-LAST:event_btnActActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAct;
    private javax.swing.JButton btnRegistrarC;
    public javax.swing.JComboBox cmbCatCurso;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAgregarCurso;
    private javax.swing.JLabel lblDescripC;
    private javax.swing.JLabel lblDuracionC;
    private javax.swing.JLabel lblNombreC;
    private javax.swing.JLabel lblReqEspecif;
    private javax.swing.JTextField txtDuracionC;
    private javax.swing.JTextField txtNombreC;
    private javax.swing.JTextArea txtaDescripC;
    private javax.swing.JTextArea txtaReqEspesifC;
    // End of variables declaration//GEN-END:variables
}
