/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package poo.interfaz;

import java.util.LinkedList;
import javax.swing.JOptionPane;

/**
 *
 * @author FAMILIA Cach
 */
public class AgregarCategoria extends javax.swing.JPanel {

    static Registros registro3 = new Registros();
    //LinkedList<Categoria>
            
    public AgregarCategoria() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNombreCategoria = new javax.swing.JLabel();
        lblDescripcionCategoria = new javax.swing.JLabel();
        txtNombreCategoria = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaDescripCateg = new javax.swing.JTextArea();
        btnAgregarCategoria = new javax.swing.JButton();

        setBackground(new java.awt.Color(135, 167, 231));

        lblNombreCategoria.setFont(new java.awt.Font("Myanmar Text", 0, 12)); // NOI18N
        lblNombreCategoria.setText("Nombre de la Categoría: ");

        lblDescripcionCategoria.setFont(new java.awt.Font("Myanmar Text", 1, 12)); // NOI18N
        lblDescripcionCategoria.setText("Descripción de la Categoría: ");

        txaDescripCateg.setColumns(20);
        txaDescripCateg.setRows(5);
        jScrollPane1.setViewportView(txaDescripCateg);

        btnAgregarCategoria.setFont(new java.awt.Font("Myanmar Text", 1, 12)); // NOI18N
        btnAgregarCategoria.setText("Agregar Categoría");
        btnAgregarCategoria.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAgregarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarCategoriaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDescripcionCategoria)
                                    .addComponent(lblNombreCategoria))
                                .addGap(33, 33, 33)
                                .addComponent(txtNombreCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(btnAgregarCategoria)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreCategoria)
                    .addComponent(txtNombreCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(lblDescripcionCategoria)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAgregarCategoria)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public LinkedList<Categoria> pasarCategoria(){
        return registro3.categorias;
    }
    
    private void btnAgregarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarCategoriaActionPerformed
        // TODO add your handling code here:
        
        /*PRUEBA 1: ENVIAR LOS DATOS A CURSOSDISPONIBLES*/
        
        //CursosDisponibles enviodatos = new CursosDisponibles();
        
        //enviodatos.cmbCategorias = (String)txtNombreCategoria.getText();
        
        
        /*HASTA AQUI */
        String nombreCtegora=(String)txtNombreCategoria.getText();
        String descripCateg=txaDescripCateg.getText();
        
        if("".equals(nombreCtegora)){
            JOptionPane.showMessageDialog(null,"Es nesario poner nombre a la categoría");
            /*for(int i=0;i<categorias.size();i++){
                aux=categorias.get(i);
                if(aux==nuevaCategoria){
                    JOptionPane.showMessageDialog(null, "La categoría ingresada ya existe");
                }else{
                    categorias.add(nuevaCategoria);
                }
            }*/
        }else{
            registro3.categorias.add(new Categoria(nombreCtegora,descripCateg));
            for(int i=registro3.categorias.size()-1;i<registro3.categorias.size();i++){
                Categoria aux;
                aux=registro3.categorias.get(i);
                registro3.curDisponible.cmbCategorias.addItem(registro3.categorias.get(i).getNombre());
                //registro3.curDisponible.cmbCategorias.addItem(txtNombreCategoria);
                //registro3.curDisponible.cmbCategorias.addItem(registro3.agregCategoria.txtNombreCategoria);
                
                registro3.agrCurso.cmbCatCurso.addItem(registro3.categorias.get(i).getNombre());
            }
        }
    }//GEN-LAST:event_btnAgregarCategoriaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarCategoria;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDescripcionCategoria;
    private javax.swing.JLabel lblNombreCategoria;
    private javax.swing.JTextArea txaDescripCateg;
    private javax.swing.JTextField txtNombreCategoria;
    // End of variables declaration//GEN-END:variables
}
