/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package poo.interfaz;

import java.util.LinkedList;
import javax.swing.JOptionPane;

/**
 *
 * @author FAMILIA Cach
 */
public class RegistrarDocente extends javax.swing.JPanel {

    static Registros registro2 = new Registros();
    
    public RegistrarDocente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNombreD = new javax.swing.JLabel();
        lblApellidoD = new javax.swing.JLabel();
        lblCedulaD = new javax.swing.JLabel();
        lblcorreoElectronicoD = new javax.swing.JLabel();
        lblPresentacionD = new javax.swing.JLabel();
        lblCelularD = new javax.swing.JLabel();
        lblProfCurso = new javax.swing.JLabel();
        txtNombreD = new javax.swing.JTextField();
        txtApellidoD = new javax.swing.JTextField();
        txtCedulaD = new javax.swing.JTextField();
        txtcorreoElectronicoD = new javax.swing.JTextField();
        txtPresentacionD = new javax.swing.JTextField();
        txtCelularD = new javax.swing.JTextField();
        cmbCursoProfe = new javax.swing.JComboBox();
        btnRegistrarDocente = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();

        setBackground(new java.awt.Color(135, 167, 231));

        lblNombreD.setFont(new java.awt.Font("Myanmar Text", 0, 12)); // NOI18N
        lblNombreD.setText("Nombre: ");

        lblApellidoD.setFont(new java.awt.Font("Myanmar Text", 0, 12)); // NOI18N
        lblApellidoD.setText("Apellido: ");

        lblCedulaD.setFont(new java.awt.Font("Myanmar Text", 0, 12)); // NOI18N
        lblCedulaD.setText("Cedula: ");

        lblcorreoElectronicoD.setFont(new java.awt.Font("Myanmar Text", 0, 12)); // NOI18N
        lblcorreoElectronicoD.setText("Correo Electrónico: ");

        lblPresentacionD.setFont(new java.awt.Font("Myanmar Text", 0, 12)); // NOI18N
        lblPresentacionD.setText("Presentación: ");

        lblCelularD.setFont(new java.awt.Font("Myanmar Text", 0, 12)); // NOI18N
        lblCelularD.setText("Número Celular: ");

        lblProfCurso.setFont(new java.awt.Font("Myanmar Text", 0, 12)); // NOI18N
        lblProfCurso.setText("Profesor del Curso: ");

        btnRegistrarDocente.setFont(new java.awt.Font("Myanmar Text", 1, 12)); // NOI18N
        btnRegistrarDocente.setText("Registrar ");
        btnRegistrarDocente.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRegistrarDocente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarDocenteActionPerformed(evt);
            }
        });

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblcorreoElectronicoD)
                    .addComponent(lblPresentacionD)
                    .addComponent(lblCelularD)
                    .addComponent(lblProfCurso)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblApellidoD)
                        .addComponent(lblNombreD))
                    .addComponent(lblCedulaD))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNombreD)
                    .addComponent(txtApellidoD)
                    .addComponent(txtCedulaD)
                    .addComponent(txtcorreoElectronicoD)
                    .addComponent(txtPresentacionD)
                    .addComponent(txtCelularD)
                    .addComponent(cmbCursoProfe, 0, 154, Short.MAX_VALUE))
                .addContainerGap(78, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(btnRegistrarDocente, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnActualizar)
                .addGap(43, 43, 43))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreD)
                    .addComponent(txtNombreD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblApellidoD)
                    .addComponent(txtApellidoD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCedulaD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCedulaD))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcorreoElectronicoD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblcorreoElectronicoD))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPresentacionD)
                    .addComponent(txtPresentacionD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCelularD)
                    .addComponent(txtCelularD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProfCurso)
                    .addComponent(cmbCursoProfe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrarDocente)
                    .addComponent(btnActualizar))
                .addGap(31, 31, 31))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarDocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarDocenteActionPerformed
        // TODO add your handling code here:
        try{
          AgregarCurso objRCProf=new AgregarCurso();
          LinkedList<Curso> cursos= new LinkedList<>();
          cursos=objRCProf.pasarCurso();
        //
        String nombre =txtNombreD.getText();
        String apellido =txtApellidoD.getText();
        String cedula =txtCedulaD.getText();
        String correo =txtcorreoElectronicoD.getText();
        String presentacion =txtPresentacionD.getText();
        int celular =Integer.parseInt((String)txtCelularD.getText());
        String cursoCocente =(String)cmbCursoProfe.getSelectedItem();
        //p= new Estudiante(nombre,apellido,cedula,correo);
        registro2.docente=new LinkedList<Persona>();
        if("".equals(nombre)==false&&"".equals(apellido)==false&&(Persona.validarCorreoGmail(correo)==true||Persona.validarCorreoHotmailES(correo)==true||
            Persona.validarCorreoHotmailCOM(correo)==true||Persona.validarCorreoInstitucional(correo)==true)
                ){
            System.out.println("A");//
            if(Persona.validacionCedula(cedula)==true){
                registro2.docente.add(new Docente(presentacion,celular,nombre,apellido,cedula,correo));
                Curso auxC;
                Persona auxD;
                System.out.println("B");//
                for(int i=0;i<objRCProf.pasarCurso().size();i++){
                    System.out.println("C");//
                   auxC=objRCProf.pasarCurso().get(i);
                   //JOptionPane.showMessageDialog(null,curso.size());
                    if(cursoCocente==auxC.getNombre()){
                        System.out.println("D");
                            objRCProf.pasarCurso().get(i).setDocente((Docente)registro2.docente.get(i));
                            
                    }
                }

              JOptionPane.showMessageDialog(null, "Docente registrado exitosamente",
                "Información Guardada", JOptionPane.INFORMATION_MESSAGE);
            }else{
                JOptionPane.showMessageDialog(null, "Cedula invalida",
                "Error", JOptionPane.ERROR_MESSAGE);
            }
            
        }else{
            JOptionPane.showMessageDialog(null, "El correo ingresado no es valido o algún campo no fue llenado",
                "Error", JOptionPane.ERROR_MESSAGE);
        }
        }catch(Exception e){
                //JOptionPane.showMessageDialog(rootPane,"Error"+e);
                }
    }//GEN-LAST:event_btnRegistrarDocenteActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        cmbCursoProfe.removeAllItems();
        AgregarCurso objRC=new AgregarCurso();
        LinkedList<Curso> cursos= new LinkedList<>();
        cursos=objRC.pasarCurso();
        for(Curso c:objRC.pasarCurso()){
            cmbCursoProfe.addItem(c.getNombre());
            //System.out.println(categorias.size());
        }
    }//GEN-LAST:event_btnActualizarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnRegistrarDocente;
    public javax.swing.JComboBox cmbCursoProfe;
    private javax.swing.JLabel lblApellidoD;
    private javax.swing.JLabel lblCedulaD;
    private javax.swing.JLabel lblCelularD;
    private javax.swing.JLabel lblNombreD;
    private javax.swing.JLabel lblPresentacionD;
    private javax.swing.JLabel lblProfCurso;
    private javax.swing.JLabel lblcorreoElectronicoD;
    private javax.swing.JTextField txtApellidoD;
    private javax.swing.JTextField txtCedulaD;
    private javax.swing.JTextField txtCelularD;
    private javax.swing.JTextField txtNombreD;
    private javax.swing.JTextField txtPresentacionD;
    private javax.swing.JTextField txtcorreoElectronicoD;
    // End of variables declaration//GEN-END:variables
}
