/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package poo.interfaz;

import java.util.ArrayList;
import java.util.LinkedList;

/**
 *
 * @author FAMILIA Cach
 */
public class ReporteEstudiantes extends javax.swing.JPanel {

    static Registros registro7 = new Registros();
    
    public ReporteEstudiantes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblReporteEst = new javax.swing.JLabel();
        btnReporteEstudiantes = new javax.swing.JButton();
        lblEstRegis = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtaReporteEst = new javax.swing.JTextArea();
        lblEstMatric = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtaEstMatric = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(135, 167, 231));

        lblReporteEst.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        lblReporteEst.setText("Reporte Estudiantes");

        btnReporteEstudiantes.setFont(new java.awt.Font("Myanmar Text", 1, 12)); // NOI18N
        btnReporteEstudiantes.setText("Reporte");
        btnReporteEstudiantes.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnReporteEstudiantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteEstudiantesActionPerformed(evt);
            }
        });

        lblEstRegis.setFont(new java.awt.Font("Myanmar Text", 1, 12)); // NOI18N
        lblEstRegis.setText("Estudiantes Registrados");

        txtaReporteEst.setColumns(20);
        txtaReporteEst.setRows(5);
        jScrollPane1.setViewportView(txtaReporteEst);

        lblEstMatric.setFont(new java.awt.Font("Myanmar Text", 1, 12)); // NOI18N
        lblEstMatric.setText("Estudiantes Matriculados");

        txtaEstMatric.setColumns(20);
        txtaEstMatric.setRows(5);
        jScrollPane2.setViewportView(txtaEstMatric);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblEstMatric)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblReporteEst)
                                    .addComponent(lblEstRegis))
                                .addGap(26, 26, 26)
                                .addComponent(btnReporteEstudiantes, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblReporteEst)
                        .addGap(15, 15, 15)
                        .addComponent(lblEstRegis)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnReporteEstudiantes)
                        .addGap(23, 23, 23)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEstMatric)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnReporteEstudiantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteEstudiantesActionPerformed
        // TODO add your handling code here:
        Persona auxE;
        String contenedor="";
        String contenedor1="";
        String contenedor2="";
        String contenedor3="";
        RegistrarEstudiante objRE=new RegistrarEstudiante();
        LinkedList<Persona> estudiantes= new LinkedList<>();
        estudiantes=objRE.pasarEstudiante();
        
        /*for(Persona c:objRE.pasarEstudiante()){
            cmbCedulaM.addItem(c.getCedula());
            //System.out.println(categorias.size());
        }*/
        for(int i=0; i<objRE.pasarEstudiante().size();i++){
            auxE=objRE.pasarEstudiante().get(i);
            contenedor= auxE.toString();
            contenedor1=contenedor1+"\n"+contenedor;
        }
        txtaReporteEst.setText(contenedor1);
        
        CursosDisponibles objArrMat=new CursosDisponibles();
        ArrayList<String> estudMatric= new ArrayList<>();
        estudMatric=objArrMat.pasararrayMatricula();
        for(int i=0; i<objArrMat.pasararrayMatricula().size();i++){
            if(i%2==0){
                contenedor2= objArrMat.pasararrayMatricula().get(i)+"\n";
            }else{
                contenedor2= objArrMat.pasararrayMatricula().get(i)+"   ";
            }
            contenedor3=contenedor2+contenedor3;
        }
        txtaEstMatric.setText("  N. Cedula\tCurso\n"+contenedor3);
    }//GEN-LAST:event_btnReporteEstudiantesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReporteEstudiantes;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblEstMatric;
    private javax.swing.JLabel lblEstRegis;
    private javax.swing.JLabel lblReporteEst;
    private javax.swing.JTextArea txtaEstMatric;
    private javax.swing.JTextArea txtaReporteEst;
    // End of variables declaration//GEN-END:variables
}
