/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package poo.cap1.ej2;

import javax.swing.JOptionPane;

/**
 *
 * @author Marcela
 */
public class GUIAnimales extends javax.swing.JFrame {

    Animal[] animales;
    int contador;

    /**
     * Creates new form GUIAnimales
     */
    public GUIAnimales() {
        initComponents();
        //el arreglo de animales debe tener 5 elementos
        animales = new Animal[5];
        contador = 0;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgAnimales = new javax.swing.ButtonGroup();
        rbtGato = new javax.swing.JRadioButton();
        rbtConejo = new javax.swing.JRadioButton();
        rbtPerro = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaInformacion = new javax.swing.JTextArea();
        btnAgregar = new javax.swing.JButton();
        btnVerAnimales = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btgAnimales.add(rbtGato);
        rbtGato.setText("Gato");

        btgAnimales.add(rbtConejo);
        rbtConejo.setText("Conejo");

        btgAnimales.add(rbtPerro);
        rbtPerro.setText("Perro");

        txaInformacion.setColumns(20);
        txaInformacion.setRows(5);
        jScrollPane1.setViewportView(txaInformacion);

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnVerAnimales.setText("Ver Animales");
        btnVerAnimales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerAnimalesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(138, 138, 138)
                .addComponent(btnVerAnimales, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(rbtConejo, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82)
                .addComponent(rbtGato, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(145, 145, 145)
                .addComponent(rbtPerro, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 609, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtConejo)
                    .addComponent(rbtGato)
                    .addComponent(rbtPerro))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar)
                    .addComponent(btnVerAnimales))
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        //verificar que radio button esta seleccionado y crear una instancia
        //colocar esa instancia en la posicion adecuada dentro del arreglo
        try {
            if (rbtConejo.isSelected()) {
                animales[contador] = new Conejo();
            }
            if (rbtGato.isSelected()) {
                animales[contador] = new Gato();
            }
            if (rbtPerro.isSelected()) {
                animales[contador] = new Perro();
            }
            contador++;
            JOptionPane.showMessageDialog(rootPane, "El animal seleccionado se agrego al arreglo.");
        } catch (ArrayIndexOutOfBoundsException e) {
            JOptionPane.showMessageDialog(rootPane, "No se puede guardar en el arreglo");
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnVerAnimalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerAnimalesActionPerformed
        // TODO add your handling code here:

        /*
        1 El índice que ocupa el animal en el arreglo, el tipo de animal al que corresponde.
        2 El alimento favorito en el caso de perros y gatos: croquetas, en el caso de conejos: alfalfa
        3 El sonido que emite si es un perro (guau guau guau) si es un gato (miau miau miau)
         */
        // limpiar el area de texto
        txaInformacion.setText("");
        for (int i = 0; i < animales.length; i++) {
            txaInformacion.setText(txaInformacion.getText()+" En el indice " + i + " se guardo un "
                    + animales[i].getClass().getSimpleName()
                    + " el alimento favorito es " + animales[i].verComidaFavorita());
            if (animales[i] instanceof Mascota) {
              txaInformacion.setText(txaInformacion.getText()+" "+
                      ((Mascota) animales[i]).emitirSonido()+"\n");
            }
        }

    }//GEN-LAST:event_btnVerAnimalesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIAnimales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIAnimales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIAnimales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIAnimales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIAnimales().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btgAnimales;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnVerAnimales;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbtConejo;
    private javax.swing.JRadioButton rbtGato;
    private javax.swing.JRadioButton rbtPerro;
    private javax.swing.JTextArea txaInformacion;
    // End of variables declaration//GEN-END:variables
}
