/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package poo.cap1.ej2;

//mport com.paa.utilidades.Validador;
import java.util.ArrayList;
import java.util.StringTokenizer;
import javax.swing.JOptionPane;

/**
 *
 * @author Marcela
 */
public class GUIConejo extends javax.swing.JFrame {

    Conejo miConejo;
    int contador = 1000;
    static ArrayList<Conejo> conejos;

    /**
     * Creates new form GUIConejo
     */
    public GUIConejo() {
        initComponents();
        lblMensajeErrorNombre.setVisible(false);
        conejos = new ArrayList<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgSexo = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        pnlDatos = new javax.swing.JPanel();
        lblPeso = new javax.swing.JLabel();
        lblEdad = new javax.swing.JLabel();
        txtPeso = new javax.swing.JTextField();
        txtEdad = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtTasaDeCrecimiento = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cmbRaza = new javax.swing.JComboBox<>();
        lblMensajeErrorNombre = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaInformacion = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        rbtMacho = new javax.swing.JRadioButton();
        rbtHembra = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        chkAlfalfa = new javax.swing.JCheckBox();
        chkHeno = new javax.swing.JCheckBox();
        chkZanahorias = new javax.swing.JCheckBox();
        chkFrutas = new javax.swing.JCheckBox();
        btnGuardar = new javax.swing.JButton();
        btnDiagnosticar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txaDiagnostico = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txaAlimentosFavoritos = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txaDescripcion = new javax.swing.JTextArea();
        btnContarPalabras = new javax.swing.JButton();
        btnContarOraciones = new javax.swing.JButton();
        btnGuardarDescripcion = new javax.swing.JButton();
        btnNumeroConejosCreados = new javax.swing.JButton();
        btnVerEdad = new javax.swing.JButton();

        setTitle("CONEJO");

        pnlDatos.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos"));

        lblPeso.setText("Peso");

        lblEdad.setText("Edad");

        jLabel1.setText("Nombre");

        jLabel2.setText("Tasa de Crecimiento");

        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNombreKeyReleased(evt);
            }
        });

        jLabel3.setText("Raza");

        cmbRaza.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Angora", "Californiano", "Cabeza de Leon", "Papillon", "Renard" }));

        lblMensajeErrorNombre.setForeground(new java.awt.Color(255, 0, 51));
        lblMensajeErrorNombre.setText("Debe ingresar letras");

        javax.swing.GroupLayout pnlDatosLayout = new javax.swing.GroupLayout(pnlDatos);
        pnlDatos.setLayout(pnlDatosLayout);
        pnlDatosLayout.setHorizontalGroup(
            pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDatosLayout.createSequentialGroup()
                        .addComponent(lblPeso)
                        .addGap(43, 43, 43)
                        .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblEdad))
                .addGap(18, 18, 18)
                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlDatosLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTasaDeCrecimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlDatosLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(63, 63, 63)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDatosLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(cmbRaza, 0, 107, Short.MAX_VALUE))
                    .addGroup(pnlDatosLayout.createSequentialGroup()
                        .addComponent(lblMensajeErrorNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlDatosLayout.setVerticalGroup(
            pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPeso)
                    .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblMensajeErrorNombre)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEdad)
                    .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtTasaDeCrecimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(cmbRaza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49))
        );

        txaInformacion.setColumns(20);
        txaInformacion.setRows(5);
        jScrollPane1.setViewportView(txaInformacion);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Sexo"));

        btgSexo.add(rbtMacho);
        rbtMacho.setText("Macho");
        rbtMacho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtMachoActionPerformed(evt);
            }
        });

        btgSexo.add(rbtHembra);
        rbtHembra.setText("Hembra");
        rbtHembra.setToolTipText("");
        rbtHembra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtHembraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rbtHembra, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbtMacho, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(rbtMacho)
                .addGap(27, 27, 27)
                .addComponent(rbtHembra)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Dieta"));

        chkAlfalfa.setText("Alfalfa");

        chkHeno.setText("Heno");

        chkZanahorias.setText("Zanahorias");

        chkFrutas.setText("Frutas");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkAlfalfa, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkHeno, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkZanahorias, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkFrutas, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chkAlfalfa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chkFrutas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chkHeno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chkZanahorias)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnDiagnosticar.setText("Diagnosticar");
        btnDiagnosticar.setEnabled(false);
        btnDiagnosticar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDiagnosticarActionPerformed(evt);
            }
        });

        txaDiagnostico.setColumns(20);
        txaDiagnostico.setRows(5);
        jScrollPane2.setViewportView(txaDiagnostico);

        txaAlimentosFavoritos.setColumns(20);
        txaAlimentosFavoritos.setRows(5);
        jScrollPane3.setViewportView(txaAlimentosFavoritos);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Descripcion"));

        txaDescripcion.setColumns(20);
        txaDescripcion.setRows(5);
        jScrollPane4.setViewportView(txaDescripcion);

        btnContarPalabras.setText("Contar palabras");
        btnContarPalabras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContarPalabrasActionPerformed(evt);
            }
        });

        btnContarOraciones.setText("Contar oraciones");
        btnContarOraciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContarOracionesActionPerformed(evt);
            }
        });

        btnGuardarDescripcion.setText("Guardar descripción");
        btnGuardarDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarDescripcionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnContarPalabras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnContarOraciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGuardarDescripcion, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnContarPalabras)
                        .addGap(39, 39, 39)
                        .addComponent(btnContarOraciones)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnGuardarDescripcion)
                        .addGap(38, 38, 38))))
        );

        btnNumeroConejosCreados.setText("# de conejos creados");
        btnNumeroConejosCreados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumeroConejosCreadosActionPerformed(evt);
            }
        });

        btnVerEdad.setText("Ver edad conejo adulto");
        btnVerEdad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerEdadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(148, 148, 148)
                                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(75, 75, 75)
                                .addComponent(btnDiagnosticar)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnNumeroConejosCreados)
                                .addGap(33, 33, 33)
                                .addComponent(btnVerEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDiagnosticar)
                    .addComponent(btnNumeroConejosCreados)
                    .addComponent(btnGuardar)
                    .addComponent(btnVerEdad))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        //  JOptionPane.showMessageDialog(null, "Buenas tardes", "Saludo", JOptionPane.INFORMATION_MESSAGE);
        /*Utilizar variables locales para guardar el peso, edad, tasa de crecimiento y nombre
              que el usr ingreso en las cajas de texto*/
        String nombre = txtNombre.getText();

        String peso = txtPeso.getText();
        double pesoDelConejo;
        try {
            pesoDelConejo = Double.parseDouble(txtPeso.getText()); //exp NumberFormatException
            String edad = txtEdad.getText();
            String tasaCrecimiento = txtTasaDeCrecimiento.getText();
            miConejo = new Conejo(Integer.parseInt(edad), Double.parseDouble(tasaCrecimiento),
                    pesoDelConejo, nombre, contador); //excp
            //utilizar el metodo toString para presentar la informacion del conejo en el area de texto
            String raza = (String) cmbRaza.getSelectedItem();
            miConejo.setRaza(raza);
            //para el sexo del conejo si el usr marco Hembra el sexo es FEMENINO
            //si el usr marco Macho el sexo es MASCULINO
            if (rbtHembra.isSelected()) {
                miConejo.setSexo("FEMENINO");
            }
            if (rbtMacho.isSelected()) {
                miConejo.setSexo("MASCULINO");
            }
            //Verificar si la casilla de dieta esa seleccionada y guardar en un String
            String dieta = "";
            String dietaSeleccionada[] = new String[4];
            int indice = 0;
            if (chkAlfalfa.isSelected()) {
                dieta += chkAlfalfa.getText();
                dieta += " ";
                dietaSeleccionada[indice] = chkAlfalfa.getText();
                indice++;
            }

            if (chkHeno.isSelected()) {
                dieta += chkHeno.getText();
                dieta += " ";
                dietaSeleccionada[indice] = chkHeno.getText();
                indice++;
            }

            if (chkZanahorias.isSelected()) {
                dieta += chkZanahorias.getText();
                dietaSeleccionada[indice] = chkZanahorias.getText();
                indice++;
            }

            if (chkFrutas.isSelected()) {
                dietaSeleccionada[indice] = chkFrutas.getText();
            }
            miConejo.setAlimentosFavoritos(dietaSeleccionada);

            txaAlimentosFavoritos.setText(miConejo.mostrarAlimentosFavoritos());

            //luego de verificar las 3 casillas utilice el  setDieta para guardar la dieta del conejo
            miConejo.setDieta(dieta);
            txaInformacion.setText(txaInformacion.getText() + miConejo.toString() + "\n");
            btnDiagnosticar.setEnabled(true);
            contador++;
            conejos.add(miConejo);
        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(rootPane, "El peso, la edad y tasa de crecimiento"
                    + " deben ser números", "Error", JOptionPane.WARNING_MESSAGE);
        } catch (NullPointerException npe) {
            JOptionPane.showMessageDialog(rootPane, "Error al crear el objeto" + npe.getMessage());
            npe.printStackTrace();
        }/* catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "EXCEPCION " + e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }*/

        limpiarGUI();

    }//GEN-LAST:event_btnGuardarActionPerformed

    private void rbtMachoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtMachoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtMachoActionPerformed

    private void rbtHembraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtHembraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtHembraActionPerformed

    private void btnDiagnosticarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDiagnosticarActionPerformed
        // TODO add your handling code here:
        Veterinario vet = new Veterinario(); //crear el obj
        String diagnostico = vet.diagnosticar(miConejo.getNombre(), miConejo.getEdad(), miConejo.getPeso());
        txaDiagnostico.setText(diagnostico);
    }//GEN-LAST:event_btnDiagnosticarActionPerformed

    private void btnContarPalabrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContarPalabrasActionPerformed
        // TODO add your handling code here:
        StringTokenizer tokensDePalabras = new StringTokenizer(txaDescripcion.getText()); //LOS caracteres delimitadores son: espacio, salto de linea, tab
        JOptionPane.showMessageDialog(rootPane, "Se obtuvieron " + tokensDePalabras.countTokens() + " palabras");


    }//GEN-LAST:event_btnContarPalabrasActionPerformed

    private void btnContarOracionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContarOracionesActionPerformed
        // TODO add your handling code here:
        StringTokenizer tokensDeOraciones = new StringTokenizer(txaDescripcion.getText(), "."); //especifico explicitamente el delimitador como arg
        JOptionPane.showMessageDialog(rootPane, "Se obtuvieron " + tokensDeOraciones.countTokens() + " oraciones");
        while (tokensDeOraciones.hasMoreTokens()) {
            JOptionPane.showMessageDialog(rootPane, tokensDeOraciones.nextToken());
        }
    }//GEN-LAST:event_btnContarOracionesActionPerformed

    private void btnGuardarDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarDescripcionActionPerformed
        // TODO add your handling code here:
        String descripcion[] = txaDescripcion.getText().split("\\.");//lista inicializadora 
        miConejo.setDescripcion(descripcion);
        //utilizar un for para recorrer la variable de instancia descripcion y mostrar el contenido 
        JOptionPane.showMessageDialog(rootPane, "Se ingresaron " + miConejo.getDescripcion().length + " oraciones que describen al conejo");
        for (String d : miConejo.getDescripcion())
            JOptionPane.showMessageDialog(rootPane, d);
    }//GEN-LAST:event_btnGuardarDescripcionActionPerformed

    private void txtNombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyReleased
        // TODO add your handling code here:
        //Utilizar el metodo verificarNombre y acorde al resultado
        //mostrar u ocultar la etiqueta de error
        // JOptionPane.showMessageDialog(rootPane, "La tecla pulsada fue "+evt.getKeyChar());
      /*  if (Validador.verificarNombre(txtNombre.getText())) {
            lblMensajeErrorNombre.setVisible(false);
        } else {
            lblMensajeErrorNombre.setVisible(true);
        }*/

    }//GEN-LAST:event_txtNombreKeyReleased

    private void btnNumeroConejosCreadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumeroConejosCreadosActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(rootPane, "La cantidad de conejos creados hasta el momento es " + Conejo.getContadorConejosCreados());
    }//GEN-LAST:event_btnNumeroConejosCreadosActionPerformed

    private void btnVerEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerEdadActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(rootPane, "La edad a la que un conejo es adulto es " + Conejo.getEDAD_CONEJO_ADULTO() + " dias");
    }//GEN-LAST:event_btnVerEdadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIConejo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIConejo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIConejo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIConejo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIConejo().setVisible(true);
            }
        });
    }

    public void limpiarGUI() {
        //permite preparar la GUI para un nuevo ingreso
        //visualmente los componentes deben presentarse vacios
        txtEdad.setText(null);
        txtPeso.setText(null);
        txtNombre.setText("");
        txtTasaDeCrecimiento.setText(null);
        btgSexo.clearSelection(); //
        //establecer el item seleccionado del comboBox al primer elemento
        cmbRaza.setSelectedIndex(0);
        chkZanahorias.setSelected(false);
        chkAlfalfa.setSelected(false);
        chkHeno.setSelected(false);
        chkFrutas.setSelected(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btgSexo;
    private javax.swing.JButton btnContarOraciones;
    private javax.swing.JButton btnContarPalabras;
    private javax.swing.JButton btnDiagnosticar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnGuardarDescripcion;
    private javax.swing.JButton btnNumeroConejosCreados;
    private javax.swing.JButton btnVerEdad;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox chkAlfalfa;
    private javax.swing.JCheckBox chkFrutas;
    private javax.swing.JCheckBox chkHeno;
    private javax.swing.JCheckBox chkZanahorias;
    private javax.swing.JComboBox<String> cmbRaza;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblEdad;
    private javax.swing.JLabel lblMensajeErrorNombre;
    private javax.swing.JLabel lblPeso;
    private javax.swing.JPanel pnlDatos;
    private javax.swing.JRadioButton rbtHembra;
    private javax.swing.JRadioButton rbtMacho;
    private javax.swing.JTextArea txaAlimentosFavoritos;
    private javax.swing.JTextArea txaDescripcion;
    private javax.swing.JTextArea txaDiagnostico;
    private javax.swing.JTextArea txaInformacion;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPeso;
    private javax.swing.JTextField txtTasaDeCrecimiento;
    // End of variables declaration//GEN-END:variables
}
